// Mock database (customers)
const customerDB = [
    {
        id: 1,
        cifID:123456789,
        date: "2024-04-25",
        BVN: "1234567890",
        title: "Mr.",
        firstName: "Thelma",
        middleName: "",
        lastName: "Akpata",
        fullName: "Thelma Akpata",
        DOB: "1990-01-01",
        email: "thelma@example.com",
        phoneNumber: "1234567890",
        gender: "Male",
        maritalStatus: "Single",
        countryOfResidence: "Nigeria",
        address: "123 Main St, New York, NY",
        occupation: "Software Engineer"
    },
    {
        id: 2,
        cifID:123456788,
        date: "2024-04-25",
        BVN: "0987654321",
        title: "Ms.",
        firstName: "Alice",
        lastName: "Smith",
        fullName: "Alice Smith",
        DOB: "1985-05-15",
        email: "alice@example.com",
        phoneNumber: "9876543210",
        gender: "Female",
        maritalStatus: "Married",
        countryOfResidence: "Nigeria",
        address: "456 Maple Ave, Toronto, ON",
        occupation: "Doctor"
    },
    {
        id: 3,
        cifID:123456787,
        date: "2024-04-25",
        BVN: "9876543210",
        title: "Dr.",
        firstName: "Michael",
        middleName: "Alan",
        lastName: "Osaigbovo",
        fullName: "Michael Alan Osaigbovo",
        DOB: "1978-09-30",
        email: "michael.osas@example.com",
        phoneNumber: "8765432109",
        gender: "Male",
        maritalStatus: "Married",
        countryOfResidence: "Nigeria",
        address: "789 Oak St, London, UK",
        occupation: "Teacher"
    },
    {
        id: 4,
        cifID:123456786,
        date: "2024-04-25",
        BVN: "2345678901",
        title: "Mr.",
        firstName: "Emeka",
        lastName: "Obi",
        fullName: "Emeka Obi",
        DOB: "1982-06-10",
        email: "emeka.obi@example.com",
        phoneNumber: "2345678901",
        gender: "Male",
        maritalStatus: "Single",
        countryOfResidence: "Nigeria",
        address: "12 Ikoyi Rd, Lagos",
        occupation: "Civil Engineer"
    },
    {
        id: 5,
        cifID:123456785,
        date: "2024-04-25",
        BVN: "3456789012",
        title: "Ms.",
        firstName: "Ada",
        lastName: "Nwosu",
        fullName: "Ada Nwosu",
        DOB: "1992-12-14",
        email: "ada.nwosu@example.com",
        phoneNumber: "3456789012",
        gender: "Female",
        maritalStatus: "Single",
        countryOfResidence: "Nigeria",
        address: "34 Victoria Island, Lagos",
        occupation: "Accountant"
    },
    {
        id: 6,
        cifID:123456784,
        date: "2024-04-25",
        BVN: "4567890123",
        title: "Mrs.",
        firstName: "Chinelo",
        lastName: "Okafor",
        fullName: "Chinelo Okafor",
        DOB: "1987-07-21",
        email: "chinelo.okafor@example.com",
        phoneNumber: "4567890123",
        gender: "Female",
        maritalStatus: "Married",
        countryOfResidence: "Nigeria",
        address: "67 Ikeja Rd, Lagos",
        occupation: "Pharmacist"
    },
    {
        id: 7,
        cifID:123456783,
        date: "2024-04-25",
        BVN: "5678901234",
        title: "Mr.",
        firstName: "Oluwasegun",
        lastName: "Adebayo",
        fullName: "Oluwasegun Adebayo",
        DOB: "1985-04-11",
        email: "oluwasegun.adebayo@example.com",
        phoneNumber: "5678901234",
        gender: "Male",
        maritalStatus: "Married",
        countryOfResidence: "Nigeria",
        address: "89 Lekki Rd, Lagos",
        occupation: "Business Analyst"
    }
];

module.exports = customerDB;
